server:
  port: 8888
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 2s
    keep-alive-timeout: 15s

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luminecs/cnsia-config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          # 默认克隆到随机目录，但你可以指定
          # basedir: /tmp/config-repo
